#!/bin/bash

TMPFILENAME=$(mktemp /tmp/droidpatch-XXXXXX)

# Write start sequence (including sysex header)
echo -ne '\0360\0000\0146\0146P' > $TMPFILENAME
# Write content but remove comments. They might contain non-ascii characters
sed 's/#.*//' $1 >> $TMPFILENAME
# Write SYSEX end byte
echo -ne '\0367' >> $TMPFILENAME


./sendmidi dev droid syf $TMPFILENAME

if [ "$?" != 0 ]
then
    echo "Error sending MIDI SYSEX message" >&2
    rm -f $TMPFILENAME
    exit 1
else
    echo "Successfully sent $(wc -c < $TMPFILENAME) bytes to DROID X7 using $TOOL."
    rm -f $TMPFILENAME
    exit 0
fi

