#!/bin/bash

TMPFILENAME=$(mktemp /tmp/droidpatch-XXXXXX)

# Write start sequence (including sysex header)
echo '\0360\0000\0146\0146P' > $TMPFILENAME
# Write content but remove comments. They might contain non-ascii characters
sed 's/#.*//' "$1" >> $TMPFILENAME
# Write SYSEX end byte
echo '\0367' >> $TMPFILENAME

./sendmidi dev "$2" syf $TMPFILENAME

if [ "$?" != 0 ]
then
    echo "Error sending MIDI SYSEX message to device $2" >&2
    rm -f $TMPFILENAME
    exit 1
else
    echo "Successfully sent $(wc -c < $TMPFILENAME) bytes to device $2"
    rm -f $TMPFILENAME
    exit 0
fi